version: "3.1"

services:
  elasticsearch:
    container_name: elasticsearch-7.17.0
    image: elasticsearch:7.17.0
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "http.host=0.0.0.0"
      - "node.name=elastic01"
      - "cluster.name=cluster_elasticsearch"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - elk_net

  filebeat:
    container_name: video-filebeat
    image: elastic/filebeat:7.17.0
    restart: always
    user: root
    volumes:
      - ./filebeat/logs:/usr/share/filebeat/target
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/data:/usr/share/filebeat/data
    ports:
      - "9000:9000"
    networks:
      - elk_net

  logstash:
    container_name: logstash-7.17.0
    image: docker.elastic.co/logstash/logstash:7.17.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/logstash.yml
      - ./logstash/data:/usr/share/logstash/data
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - elk_net
    depends_on:
      - filebeat
      - elasticsearch


  kibana:
    container_name: kibana-7.17.0
    image: kibana:7.17.0
    ports:
      - "5601:5601"
    networks:
      - elk_net
    depends_on:
      - elasticsearch



#  mysql8:
#    container_name: mysql8
#    image: mysql:8.0
#    restart: always
#    environment:
#      - "TZ: Asia/Shanghai"
#      - "MYSQL_ROOT_PASSWORD: root"
#      - "MYSQL_DATABASE: orm_test"
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./mysql/data/:/var/lib/mysql/
#      - ./mysql/conf/:/etc/mysql/conf.d/
#      - ./mysql/init/:/docker-entrypoint-initdb.d/
#    command:
#      --default-authentication-plugin=mysql_native_password
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_general_ci
#      --explicit_defaults_for_timestamp=true
#    networks:
#      - elk_net




networks:
  elk_net:
    driver: bridge